// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rating/rating.proto

/*
Package ideas is a generated protocol buffer package.

It is generated from these files:
	proto/rating/rating.proto

It has these top-level messages:
	DeleteRatingsRequest
	DeleteRatingsResponse
	Ratings
	Rating
*/
package ideas

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeleteRatingsRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *DeleteRatingsRequest) Reset()                    { *m = DeleteRatingsRequest{} }
func (m *DeleteRatingsRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRatingsRequest) ProtoMessage()               {}
func (*DeleteRatingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeleteRatingsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type DeleteRatingsResponse struct {
}

func (m *DeleteRatingsResponse) Reset()                    { *m = DeleteRatingsResponse{} }
func (m *DeleteRatingsResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRatingsResponse) ProtoMessage()               {}
func (*DeleteRatingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Ratings struct {
	Ratings []*Rating `protobuf:"bytes,1,rep,name=ratings" json:"ratings,omitempty"`
}

func (m *Ratings) Reset()                    { *m = Ratings{} }
func (m *Ratings) String() string            { return proto.CompactTextString(m) }
func (*Ratings) ProtoMessage()               {}
func (*Ratings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ratings) GetRatings() []*Rating {
	if m != nil {
		return m.Ratings
	}
	return nil
}

type Rating struct {
	// @inject_tag: bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: bson:"user_id" valid:"required~User ID is required, uuidv4~User ID must be a valid UUIDv4" conform:"trim"
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty" bson:"user_id" valid:"required~User ID is required, uuidv4~User ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
}

func (m *Rating) Reset()                    { *m = Rating{} }
func (m *Rating) String() string            { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()               {}
func (*Rating) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Rating) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rating) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Rating) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Rating) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteRatingsRequest)(nil), "go.micro.srv.ideas.DeleteRatingsRequest")
	proto.RegisterType((*DeleteRatingsResponse)(nil), "go.micro.srv.ideas.DeleteRatingsResponse")
	proto.RegisterType((*Ratings)(nil), "go.micro.srv.ideas.ratings")
	proto.RegisterType((*Rating)(nil), "go.micro.srv.ideas.Rating")
}

func init() { proto.RegisterFile("proto/rating/rating.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x54, 0x1b, 0x3a, 0x52, 0x91, 0x45, 0x69, 0x8c, 0x07, 0x4b, 0x4e, 0xf1, 0xb2,
	0x85, 0xea, 0xc5, 0x93, 0x54, 0x7a, 0xb0, 0x08, 0x1e, 0x16, 0xbd, 0x78, 0x29, 0x69, 0x77, 0x1a,
	0x16, 0x9a, 0x6e, 0xdc, 0xdd, 0xe8, 0x2b, 0xf8, 0x26, 0xbe, 0xa6, 0x64, 0xb3, 0x11, 0xd4, 0xa0,
	0x1e, 0x3c, 0x65, 0x66, 0xf2, 0xfd, 0x33, 0xf3, 0xef, 0xc0, 0x71, 0xa1, 0xa4, 0x91, 0x63, 0x95,
	0x1a, 0xb1, 0xcd, 0xdc, 0x87, 0xda, 0x1a, 0x21, 0x99, 0xa4, 0xb9, 0x58, 0x29, 0x49, 0xb5, 0x7a,
	0xa6, 0x82, 0x63, 0xaa, 0xa3, 0xd3, 0x4c, 0xca, 0x6c, 0x83, 0x63, 0x4b, 0x2c, 0xcb, 0xf5, 0xd8,
	0x88, 0x1c, 0xb5, 0x49, 0xf3, 0xa2, 0x16, 0xc5, 0x09, 0x1c, 0xce, 0x70, 0x83, 0x06, 0x99, 0x6d,
	0xa5, 0x19, 0x3e, 0x95, 0xa8, 0x0d, 0x39, 0x80, 0xae, 0xe0, 0x3a, 0xf4, 0x46, 0xdd, 0xa4, 0xcf,
	0xaa, 0x30, 0x1e, 0xc2, 0xd1, 0x17, 0x52, 0x17, 0x72, 0xab, 0x31, 0xbe, 0x82, 0xa0, 0xde, 0x43,
	0x93, 0x8b, 0x8f, 0xd0, 0x2a, 0xf7, 0x26, 0x11, 0xfd, 0xbe, 0x14, 0xad, 0x1b, 0xb0, 0x06, 0x8d,
	0xdf, 0x3c, 0xe8, 0xd5, 0x35, 0xb2, 0x0f, 0xfe, 0x7c, 0x16, 0x7a, 0x23, 0x2f, 0xe9, 0x33, 0x7f,
	0x3e, 0x23, 0x43, 0x08, 0x4a, 0x8d, 0x6a, 0x21, 0x78, 0xe8, 0xdb, 0x62, 0xaf, 0x4a, 0xe7, 0x9c,
	0x5c, 0x02, 0xac, 0x14, 0xa6, 0x06, 0xf9, 0x22, 0x35, 0x61, 0x77, 0xe4, 0xb9, 0x61, 0x95, 0x5b,
	0xda, 0xb8, 0xa5, 0xf7, 0x8d, 0x5b, 0xd6, 0x77, 0xf4, 0xd4, 0x54, 0xd2, 0xb2, 0xe0, 0x8d, 0x74,
	0xe7, 0x77, 0xa9, 0xa3, 0xa7, 0x66, 0xf2, 0xea, 0x43, 0xe0, 0xec, 0x93, 0x1b, 0x80, 0x3b, 0x7c,
	0x69, 0xb2, 0x93, 0x36, 0xa3, 0xce, 0x60, 0xf4, 0xd3, 0xcf, 0xb8, 0x43, 0x6e, 0x61, 0xf0, 0x60,
	0x47, 0xfc, 0x47, 0xb3, 0x35, 0x0c, 0x3e, 0x9d, 0x89, 0x24, 0x6d, 0x7c, 0xdb, 0xcd, 0xa3, 0xb3,
	0x3f, 0x90, 0xee, 0xe6, 0x9d, 0xeb, 0xe0, 0x71, 0xd7, 0x02, 0xcb, 0x9e, 0x7d, 0xb2, 0xf3, 0xf7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xfb, 0xd3, 0x6d, 0x9a, 0x02, 0x00, 0x00,
}
