// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/rating/rating.proto

/*
Package rating is a generated protocol buffer package.

It is generated from these files:
	proto/rating/rating.proto

It has these top-level messages:
	DeleteRatingsRequest
	DeleteRatingsResponse
	Ratings
	Rating
*/
package rating

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for RatingService service

type RatingServiceClient interface {
	NewRatings(ctx context.Context, in *Ratings, opts ...client.CallOption) (*Ratings, error)
	UpdateRatings(ctx context.Context, in *Ratings, opts ...client.CallOption) (*Ratings, error)
	DeleteRatings(ctx context.Context, in *DeleteRatingsRequest, opts ...client.CallOption) (*DeleteRatingsResponse, error)
}

type ratingServiceClient struct {
	c           client.Client
	serviceName string
}

func NewRatingServiceClient(serviceName string, c client.Client) RatingServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.ideas"
	}
	return &ratingServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *ratingServiceClient) NewRatings(ctx context.Context, in *Ratings, opts ...client.CallOption) (*Ratings, error) {
	req := c.c.NewRequest(c.serviceName, "RatingService.NewRatings", in)
	out := new(Ratings)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) UpdateRatings(ctx context.Context, in *Ratings, opts ...client.CallOption) (*Ratings, error) {
	req := c.c.NewRequest(c.serviceName, "RatingService.UpdateRatings", in)
	out := new(Ratings)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) DeleteRatings(ctx context.Context, in *DeleteRatingsRequest, opts ...client.CallOption) (*DeleteRatingsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "RatingService.DeleteRatings", in)
	out := new(DeleteRatingsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RatingService service

type RatingServiceHandler interface {
	NewRatings(context.Context, *Ratings, *Ratings) error
	UpdateRatings(context.Context, *Ratings, *Ratings) error
	DeleteRatings(context.Context, *DeleteRatingsRequest, *DeleteRatingsResponse) error
}

func RegisterRatingServiceHandler(s server.Server, hdlr RatingServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&RatingService{hdlr}, opts...))
}

type RatingService struct {
	RatingServiceHandler
}

func (h *RatingService) NewRatings(ctx context.Context, in *Ratings, out *Ratings) error {
	return h.RatingServiceHandler.NewRatings(ctx, in, out)
}

func (h *RatingService) UpdateRatings(ctx context.Context, in *Ratings, out *Ratings) error {
	return h.RatingServiceHandler.UpdateRatings(ctx, in, out)
}

func (h *RatingService) DeleteRatings(ctx context.Context, in *DeleteRatingsRequest, out *DeleteRatingsResponse) error {
	return h.RatingServiceHandler.DeleteRatings(ctx, in, out)
}
