// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag/tag.proto

/*
Package idea is a generated protocol buffer package.

It is generated from these files:
	proto/tag/tag.proto

It has these top-level messages:
	Tag
	TagFilter
	ListTagsResponse
	UpsertTagsRequest
	UpsertTagsResponse
	DeleteTagsResponse
*/
package idea

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tag struct {
	// @inject_tag: bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: bson:"name" valid:"required~Name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~Name is required" conform:"trim"`
	// @inject_tag: bson:"slug" valid:"required~Slug is required" conform:"trim"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" bson:"slug" valid:"required~Slug is required" conform:"trim"`
	// @inject_tag: bson:"hidden"
	Hidden bool `protobuf:"varint,4,opt,name=hidden" json:"hidden,omitempty" bson:"hidden"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tag) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tag) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Tag) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type TagFilter struct {
	Ids    []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Names  []string `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
	Hidden bool     `protobuf:"varint,3,opt,name=hidden" json:"hidden,omitempty"`
}

func (m *TagFilter) Reset()                    { *m = TagFilter{} }
func (m *TagFilter) String() string            { return proto.CompactTextString(m) }
func (*TagFilter) ProtoMessage()               {}
func (*TagFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TagFilter) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *TagFilter) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *TagFilter) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type ListTagsResponse struct {
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
}

func (m *ListTagsResponse) Reset()                    { *m = ListTagsResponse{} }
func (m *ListTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTagsResponse) ProtoMessage()               {}
func (*ListTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UpsertTagsRequest struct {
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
}

func (m *UpsertTagsRequest) Reset()                    { *m = UpsertTagsRequest{} }
func (m *UpsertTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertTagsRequest) ProtoMessage()               {}
func (*UpsertTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpsertTagsRequest) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UpsertTagsResponse struct {
	Matched  int64  `protobuf:"varint,1,opt,name=matched" json:"matched,omitempty"`
	Modified int64  `protobuf:"varint,2,opt,name=modified" json:"modified,omitempty"`
	Tags     []*Tag `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *UpsertTagsResponse) Reset()                    { *m = UpsertTagsResponse{} }
func (m *UpsertTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*UpsertTagsResponse) ProtoMessage()               {}
func (*UpsertTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpsertTagsResponse) GetMatched() int64 {
	if m != nil {
		return m.Matched
	}
	return 0
}

func (m *UpsertTagsResponse) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *UpsertTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type DeleteTagsResponse struct {
	Deleted int64 `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteTagsResponse) Reset()                    { *m = DeleteTagsResponse{} }
func (m *DeleteTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTagsResponse) ProtoMessage()               {}
func (*DeleteTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteTagsResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*Tag)(nil), "go.micro.srv.ideas.Tag")
	proto.RegisterType((*TagFilter)(nil), "go.micro.srv.ideas.TagFilter")
	proto.RegisterType((*ListTagsResponse)(nil), "go.micro.srv.ideas.ListTagsResponse")
	proto.RegisterType((*UpsertTagsRequest)(nil), "go.micro.srv.ideas.UpsertTagsRequest")
	proto.RegisterType((*UpsertTagsResponse)(nil), "go.micro.srv.ideas.UpsertTagsResponse")
	proto.RegisterType((*DeleteTagsResponse)(nil), "go.micro.srv.ideas.DeleteTagsResponse")
}

func init() { proto.RegisterFile("proto/tag/tag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xd1, 0x8b, 0x13, 0x31,
	0x10, 0xc6, 0xaf, 0x4d, 0xad, 0xed, 0x1c, 0xc8, 0x39, 0xca, 0xb9, 0xac, 0x08, 0x65, 0x51, 0x29,
	0x08, 0x29, 0x9c, 0x7f, 0x80, 0xe2, 0x55, 0xb1, 0xe8, 0x8b, 0x7b, 0xbb, 0x2f, 0x82, 0x0f, 0xb9,
	0x66, 0x2e, 0x0d, 0xec, 0x36, 0xeb, 0x26, 0xbd, 0xc3, 0xbf, 0x5e, 0xd9, 0x64, 0x5b, 0xeb, 0xb5,
	0x72, 0x27, 0x72, 0x0f, 0x0b, 0xf9, 0x26, 0x93, 0xdf, 0x97, 0xfd, 0xc2, 0xc0, 0xa3, 0xaa, 0x36,
	0xce, 0x4c, 0x9c, 0x50, 0xcd, 0xc7, 0xbd, 0x42, 0x54, 0x86, 0x97, 0x7a, 0x5e, 0x1b, 0x6e, 0xeb,
	0x4b, 0xae, 0x25, 0x09, 0x1b, 0x3f, 0x55, 0xc6, 0xa8, 0x82, 0x26, 0xbe, 0xe3, 0x7c, 0x75, 0x31,
	0xa1, 0xb2, 0x72, 0x3f, 0xc2, 0x81, 0x24, 0x07, 0x96, 0x09, 0x85, 0x0f, 0xa0, 0x3b, 0x9b, 0x46,
	0x9d, 0x51, 0x67, 0x3c, 0x4c, 0xbb, 0xb3, 0x29, 0x22, 0xf4, 0x96, 0xa2, 0xa4, 0xa8, 0xeb, 0x2b,
	0x7e, 0xdd, 0xd4, 0x6c, 0xb1, 0x52, 0x11, 0x0b, 0xb5, 0x66, 0x8d, 0xc7, 0xd0, 0x5f, 0x68, 0x29,
	0x69, 0x19, 0xf5, 0x46, 0x9d, 0xf1, 0x20, 0x6d, 0x55, 0xf2, 0x09, 0x86, 0x99, 0x50, 0x1f, 0x74,
	0xe1, 0xa8, 0xc6, 0x23, 0x60, 0x5a, 0xda, 0xa8, 0x33, 0x62, 0xe3, 0x61, 0xda, 0x2c, 0xf1, 0x31,
	0xdc, 0x6b, 0x90, 0x36, 0xea, 0xfa, 0x5a, 0x10, 0x5b, 0x30, 0xf6, 0x07, 0xec, 0x0d, 0x1c, 0x7d,
	0xd6, 0xd6, 0x65, 0x42, 0xd9, 0x94, 0x6c, 0x65, 0x96, 0x96, 0xf0, 0x15, 0xf4, 0x9c, 0x50, 0x01,
	0x7a, 0x78, 0xf2, 0x84, 0xef, 0xfe, 0x37, 0xcf, 0x84, 0x4a, 0x7d, 0x53, 0xf2, 0x16, 0x1e, 0xe6,
	0x95, 0xa5, 0xba, 0x45, 0x7c, 0x5f, 0x91, 0x75, 0xff, 0x46, 0xb8, 0x02, 0xdc, 0x26, 0xb4, 0x97,
	0x88, 0xe0, 0x7e, 0x29, 0xdc, 0x7c, 0x41, 0xd2, 0x47, 0xc7, 0xd2, 0xb5, 0xc4, 0x18, 0x06, 0xa5,
	0x91, 0xfa, 0x42, 0x93, 0xf4, 0x19, 0xb2, 0x74, 0xa3, 0x37, 0xc6, 0xec, 0x36, 0xc6, 0x1c, 0x70,
	0x4a, 0x05, 0x39, 0xba, 0x6e, 0x2c, 0x7d, 0x75, 0x63, 0xdc, 0xca, 0x93, 0x9f, 0x0c, 0x0e, 0x67,
	0x92, 0xc4, 0x19, 0xd5, 0x97, 0x7a, 0x4e, 0xf8, 0x05, 0x06, 0xeb, 0xec, 0xf0, 0xd9, 0x5f, 0xac,
	0xc2, 0x33, 0xc5, 0xcf, 0xf7, 0x6d, 0x5f, 0x0f, 0x3e, 0x39, 0xc0, 0x6f, 0x00, 0xa7, 0x35, 0x89,
	0x70, 0x25, 0x7c, 0xb1, 0xef, 0xd4, 0x4e, 0xda, 0xf1, 0xcb, 0x9b, 0xda, 0xb6, 0xf1, 0x79, 0x25,
	0xef, 0x0c, 0x9f, 0x03, 0xfc, 0x0e, 0xf4, 0xa6, 0x48, 0xf6, 0x62, 0x77, 0xdf, 0x23, 0x39, 0xc0,
	0x53, 0x18, 0x7c, 0xd4, 0xf2, 0x56, 0xd0, 0x63, 0x1e, 0x06, 0x92, 0xaf, 0x07, 0x92, 0xbf, 0x6f,
	0x06, 0x32, 0x40, 0xce, 0x16, 0xe6, 0xea, 0xbf, 0x20, 0xef, 0xfa, 0x5f, 0x7b, 0x4d, 0xf3, 0x79,
	0xdf, 0xef, 0xbc, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0xee, 0x9a, 0x75, 0x20, 0x28, 0x04, 0x00,
	0x00,
}
