// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/occupation/occupation.proto

/*
Package occupation is a generated protocol buffer package.

It is generated from these files:
	proto/occupation/occupation.proto

It has these top-level messages:
	HideOccupationsRequest
	HideOccupationsResponse
	Occupations
	Occupation
*/
package occupation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HideOccupationsRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *HideOccupationsRequest) Reset()                    { *m = HideOccupationsRequest{} }
func (m *HideOccupationsRequest) String() string            { return proto.CompactTextString(m) }
func (*HideOccupationsRequest) ProtoMessage()               {}
func (*HideOccupationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HideOccupationsRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type HideOccupationsResponse struct {
}

func (m *HideOccupationsResponse) Reset()                    { *m = HideOccupationsResponse{} }
func (m *HideOccupationsResponse) String() string            { return proto.CompactTextString(m) }
func (*HideOccupationsResponse) ProtoMessage()               {}
func (*HideOccupationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Occupations struct {
	Occupations []*Occupation `protobuf:"bytes,1,rep,name=occupations" json:"occupations,omitempty"`
}

func (m *Occupations) Reset()                    { *m = Occupations{} }
func (m *Occupations) String() string            { return proto.CompactTextString(m) }
func (*Occupations) ProtoMessage()               {}
func (*Occupations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Occupations) GetOccupations() []*Occupation {
	if m != nil {
		return m.Occupations
	}
	return nil
}

type Occupation struct {
	// @inject_tag: bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"required~ID is required, uuidv4~ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: bson:"name" valid:"required~Name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~Name is required" conform:"trim"`
	// @inject_tag: bson:"hidden"
	Hidden bool `protobuf:"varint,3,opt,name=hidden" json:"hidden,omitempty" bson:"hidden"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
}

func (m *Occupation) Reset()                    { *m = Occupation{} }
func (m *Occupation) String() string            { return proto.CompactTextString(m) }
func (*Occupation) ProtoMessage()               {}
func (*Occupation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Occupation) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Occupation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Occupation) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Occupation) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Occupation) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*HideOccupationsRequest)(nil), "go.micro.srv.ideas.HideOccupationsRequest")
	proto.RegisterType((*HideOccupationsResponse)(nil), "go.micro.srv.ideas.HideOccupationsResponse")
	proto.RegisterType((*Occupations)(nil), "go.micro.srv.ideas.occupations")
	proto.RegisterType((*Occupation)(nil), "go.micro.srv.ideas.Occupation")
}

func init() { proto.RegisterFile("proto/occupation/occupation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x69, 0x41, 0x22, 0x53, 0x83, 0xba, 0x07, 0xac, 0x3d, 0x48, 0xed, 0xa9, 0xc1, 0x64,
	0x49, 0xf0, 0xe4, 0x4d, 0x0c, 0x07, 0xb9, 0x48, 0xd2, 0x60, 0x4c, 0xbc, 0x98, 0xd2, 0x1d, 0x71,
	0x13, 0xda, 0xad, 0xdd, 0xad, 0xbe, 0x93, 0x0f, 0xe1, 0xb3, 0x19, 0x96, 0x62, 0xab, 0x90, 0xe0,
	0xc1, 0xdb, 0xec, 0xee, 0xff, 0xff, 0x33, 0xf9, 0x76, 0xe0, 0x3c, 0xcd, 0x84, 0x12, 0x7d, 0x11,
	0x45, 0x79, 0x1a, 0x2a, 0x2e, 0x92, 0x4a, 0x49, 0xf5, 0x1b, 0x21, 0x73, 0x41, 0x63, 0x1e, 0x65,
	0x82, 0xca, 0xec, 0x8d, 0x72, 0x86, 0xa1, 0x74, 0xba, 0x73, 0x21, 0xe6, 0x0b, 0xec, 0x6b, 0xc5,
	0x2c, 0x7f, 0xee, 0x2b, 0x1e, 0xa3, 0x54, 0x61, 0x9c, 0xae, 0x4c, 0x5e, 0x0f, 0x3a, 0xb7, 0x9c,
	0xe1, 0xe4, 0x3b, 0x4c, 0x06, 0xf8, 0x9a, 0xa3, 0x54, 0xe4, 0x08, 0xea, 0x9c, 0x49, 0xdb, 0x70,
	0xeb, 0x7e, 0x2b, 0x58, 0x96, 0xde, 0x29, 0x9c, 0x6c, 0x68, 0x65, 0x2a, 0x12, 0x89, 0xde, 0x04,
	0xac, 0x72, 0x1e, 0x49, 0xae, 0x7f, 0x1c, 0x75, 0x86, 0x35, 0x38, 0xa3, 0x9b, 0x03, 0xd2, 0x32,
	0x2c, 0xa8, 0x5a, 0xbc, 0x4f, 0x03, 0xa0, 0x7c, 0x23, 0x6d, 0x30, 0xc7, 0x23, 0xdb, 0x70, 0x0d,
	0xbf, 0x15, 0x98, 0xe3, 0x11, 0x21, 0xd0, 0x48, 0xc2, 0x18, 0x6d, 0x53, 0xdf, 0xe8, 0x9a, 0x74,
	0xa0, 0xf9, 0xc2, 0x19, 0xc3, 0xc4, 0xae, 0xbb, 0x86, 0xbf, 0x1f, 0x14, 0x27, 0x72, 0x05, 0x10,
	0x65, 0x18, 0x2a, 0x64, 0x4f, 0xa1, 0xb2, 0x1b, 0xae, 0xe1, 0x5b, 0x03, 0x87, 0xae, 0xc0, 0xd0,
	0x35, 0x18, 0x3a, 0x5d, 0x83, 0x09, 0x5a, 0x85, 0x7a, 0xa8, 0x96, 0xd6, 0x3c, 0x65, 0x6b, 0xeb,
	0xde, 0x6e, 0x6b, 0xa1, 0x1e, 0xaa, 0xc1, 0x87, 0x09, 0x56, 0x85, 0x14, 0x99, 0x42, 0xfb, 0x0e,
	0xdf, 0xab, 0x37, 0xdd, 0x6d, 0x3c, 0x2a, 0x0c, 0x9c, 0x5d, 0x02, 0xaf, 0x46, 0x1e, 0xe0, 0xf8,
	0x5e, 0xb7, 0xfc, 0xef, 0xe0, 0x05, 0x1c, 0xfe, 0xfa, 0x6b, 0xd2, 0xdb, 0xe6, 0xda, 0xbe, 0x3c,
	0xce, 0xc5, 0x9f, 0xb4, 0xc5, 0xf2, 0xd4, 0x6e, 0x0e, 0x1e, 0xa1, 0x6c, 0x3f, 0x6b, 0x6a, 0xb2,
	0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0xd3, 0xa0, 0x5f, 0xf4, 0x02, 0x00, 0x00,
}
