// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/story/story.proto

/*
Package story is a generated protocol buffer package.

It is generated from these files:
	proto/story/story.proto

It has these top-level messages:
	DeleteStoriesRequest
	DeleteStoriesResponse
	Stories
	Story
*/
package story

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StoryService service

type StoryServiceClient interface {
	NewStories(ctx context.Context, in *Stories, opts ...client.CallOption) (*Stories, error)
	UpdateStories(ctx context.Context, in *Stories, opts ...client.CallOption) (*Stories, error)
	DeleteStories(ctx context.Context, in *DeleteStoriesRequest, opts ...client.CallOption) (*DeleteStoriesResponse, error)
}

type storyServiceClient struct {
	c           client.Client
	serviceName string
}

func NewStoryServiceClient(serviceName string, c client.Client) StoryServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.ideas"
	}
	return &storyServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *storyServiceClient) NewStories(ctx context.Context, in *Stories, opts ...client.CallOption) (*Stories, error) {
	req := c.c.NewRequest(c.serviceName, "StoryService.NewStories", in)
	out := new(Stories)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) UpdateStories(ctx context.Context, in *Stories, opts ...client.CallOption) (*Stories, error) {
	req := c.c.NewRequest(c.serviceName, "StoryService.UpdateStories", in)
	out := new(Stories)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storyServiceClient) DeleteStories(ctx context.Context, in *DeleteStoriesRequest, opts ...client.CallOption) (*DeleteStoriesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "StoryService.DeleteStories", in)
	out := new(DeleteStoriesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StoryService service

type StoryServiceHandler interface {
	NewStories(context.Context, *Stories, *Stories) error
	UpdateStories(context.Context, *Stories, *Stories) error
	DeleteStories(context.Context, *DeleteStoriesRequest, *DeleteStoriesResponse) error
}

func RegisterStoryServiceHandler(s server.Server, hdlr StoryServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&StoryService{hdlr}, opts...))
}

type StoryService struct {
	StoryServiceHandler
}

func (h *StoryService) NewStories(ctx context.Context, in *Stories, out *Stories) error {
	return h.StoryServiceHandler.NewStories(ctx, in, out)
}

func (h *StoryService) UpdateStories(ctx context.Context, in *Stories, out *Stories) error {
	return h.StoryServiceHandler.UpdateStories(ctx, in, out)
}

func (h *StoryService) DeleteStories(ctx context.Context, in *DeleteStoriesRequest, out *DeleteStoriesResponse) error {
	return h.StoryServiceHandler.DeleteStories(ctx, in, out)
}
