service:
  name: go.micro.srv.ideas
  register_ttl: 1200000
  register_interval: 10
  version: 1.0.0
  metadata:
    description: Idea service
enable_debug: true
mongodb:
  host: localhost
  db: sui
nats_streaming:
  cluster: test-cluster
  client_id: test-client

